# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy docker://docker.io/redis:6.2.16 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/redis:5.7.44
        skopeo copy docker://docker.io/redis:7.2.6 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/redis:8.0.26
        skopeo copy docker://docker.io/redis:7.4.1 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/redis:8.0.40
        skopeo copy docker://docker.io/rabbitmq:3.5.0 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/rabbitmq:3.5.0
        skopeo copy docker://docker.io/rabbitmq:3.13.7 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/rabbitmq:3.13.7
        skopeo copy docker://docker.io/elasticsearch:6.8.23 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/elasticsearch:6.8.23
        skopeo copy docker://docker.io/elasticsearch:7.10.0 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/elasticsearch:7.10.0
        skopeo copy docker://docker.io/elasticsearch:7.17.26 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/elasticsearch:7.17.26
        skopeo copy docker://docker.io/elasticsearch:8.8.1 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/elasticsearch:8.8.1
        skopeo copy docker://docker.io/elasticsearch:8.15.5 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/elasticsearch:8.15.5
        skopeo copy docker://docker.io/elasticsearch:8.16.1 docker://registry.cn-hangzhou.aliyuncs.com/qingshilu/elasticsearch:8.16.1
